<%
require 'faker'
User.all.each  do |user|
 1.upto(5) do |i| %>
 profiles_<%= user.id %>_<%= i %>:
  name: <%= Faker::Lorem .words(1).first %>
  host: <%= Common::Host::valid_options.rand %>
  user_id: <%= user.id %>
  login: <%= Faker::Internet.email %>
  password: <%= Faker::Internet.email  %>
<% end %>
<% 1.upto(2) do |i| %>
 profiles_mediavalise_<%= user.id %>_<%= i %>:
  name: <%= Faker::Lorem.words(1).first %>
  host: <%= Common::Host::MEDIAVALISE %>
  user_id: <%= user.id %>
  login: <%= Faker::Internet.email %>
  password: <%= Faker::Internet.email  %>
<% end %>
<% end %>
