defaults: &defaults
  max_active_task: 32 # размер очереди активных задач
  root_path_download: <%=  File.join(RAILS_ROOT, "data", "task_files") %> # пути куда сохраняються файлы
development:
  <<: *defaults

test: &TEST
  <<: *defaults

cucumber:
  <<: *TEST

production:
  <<: *defaults
