defaults: &defaults
  max_active_task: 40 # размер очереди активных задач
  root_path_download: <%=  File.join(RAILS_ROOT, "data", "task_files") %> # пути куда сохраняються файлы
  rar_command: rar a -m0 -inul -ep # команда архивировани, в работе еще добавляеться размер архива и список файлов

development:
  <<: *defaults

test: &TEST
  <<: *defaults

cucumber:
  <<: *TEST

production:
  <<: *defaults
