development:
  command: "aria2c --enable-xml-rpc"
  server: "localhost"
  port: "6800"
  path: "/rpc"
  user: "hydra"
  password: "hydra"
production:
  command: "aria2c --enable-xml-rpc"
  server: "localhost"
  port: "6800"
  path: "/rpc"
  user: "hydra"
  password: "hydra"
