development:
  command: "aria2c --enable-xml-rpc"
  server: "localhost"
  port: "6800"
  path: "/rpc"
  user: "hydra"
  password: "hydra"
  aria_parameters:
    log: <%= "#{RAILS_ROOT}/log/aria2c.log" %>
    log-level: 'error'
    file-allocation: 'none'

production:
  command: "aria2c --enable-xml-rpc"
  server: "localhost"
  port: "6800"
  path: "/rpc"
  user: "hydra"
  password: "hydra"
  aria_parameters:
    log: <%= "#{RAILS_ROOT}/log/aria2c.log" %>
    log-level: 'error'
    file-allocation: 'none'
    max-concurrent-downloads: '60'
    split: '10'
